 Section "InputClass"
     Identifier "libinput touchpad catchall"
     MatchIsTouchpad "on"
     MatchDevicePath "/dev/input/event*"
     Driver "libinput"
     Option "ScrollMethod" "twofinger"
     Option "ScrollPixelDistance" "10"
     Option "NaturalScrolling" "true"
     Option "Tapping" "true"
     Option "TappingButtonMap" "lrm"
     Option "DisableWhileTyping" "true"
     Option "AccelSpeed" "0.3"
     Option "ScrollDeltaMultiplier" "0.5"
 EndSection
