#!/bin/bash

# Uses 'maim' to take a mouse selection screenshot
# and opens it for drawing with 'scedit'
#
# Saves to a date organized folder structure and to
# clipboard on exit

path="$HOME/images/screenshots/$(date +%Y)/$(date +%B)"
filename=$(date +"%Y-%m-%d-%H:%M").png

[[ ! -d $path ]] && mkdir -p $path

maim -u -s | scedit -o $path/$filename -s
